
package ro.infoiasi.portocale;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Portocale", targetNamespace = "http://portocale.infoiasi.ro/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Portocale {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "furnizeazaStoc", targetNamespace = "http://portocale.infoiasi.ro/", className = "ro.infoiasi.portocale.FurnizeazaStoc")
    @ResponseWrapper(localName = "furnizeazaStocResponse", targetNamespace = "http://portocale.infoiasi.ro/", className = "ro.infoiasi.portocale.FurnizeazaStocResponse")
    public Integer furnizeazaStoc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "furnizeazaPret", targetNamespace = "http://portocale.infoiasi.ro/", className = "ro.infoiasi.portocale.FurnizeazaPret")
    @ResponseWrapper(localName = "furnizeazaPretResponse", targetNamespace = "http://portocale.infoiasi.ro/", className = "ro.infoiasi.portocale.FurnizeazaPretResponse")
    public Double furnizeazaPret();

}
